### ISSUE TITLE
osu! client doesn't restart

### ISSUE THREAD

**Issue by myangelaku** [MinisBett/ultimate-osu-server-switcher#13]
Instead of actually restarting my client, the switcher just closes it and I have to manually start it again.

**Comment by MinisBett** [comment]
Issue tracked down to https://github.com/MinisBett/ultimate-osu-server-switcher/blob/master/UltimateOsuServerSwitcher/MainForm.cs#L214

The switcher waits till the taskkill is done, not till osu really closed.
A fix would be getting the osu! process and calling WaitForExit on it instead of the taskkill process.


Will be fixed with Version 1.5

**Comment by MinisBett** [comment]
Edit: Fixed in version 2.0
