### ISSUE TITLE
Add osu!MaryJane

### ISSUE THREAD

**Issue by divinity1437** [MinisBett/ultimate-osu-server-switcher#4]
Server name: osu!MaryJane
Server URL: https://osumj.pw
Server IP: 82.146.57.125
Server certificate: https://cdn.discordapp.com/attachments/705042531582214155/715301553803755520/cert.crt
Server certificate thumbprint: 4D9B64577E55CC82CC9F35FC55CBC906C81CDAD6
Logo (48x48): http://osumj.pw/static/logos/48x48.png

**Comment by MinisBett** [comment]
We need a .cer file, a base64 encoded certificate as it is specified in the readme file. 

To get that, install the certificate and follow this tutorial: https://support.globalsign.com/ssl/ssl-certificates-installation/import-and-export-certificate-microsoft-windows

Your certificate may not be installed to the local computer, as shown in the tutorial, but on the local user. For that you chosse local user instead of the local machine when opening the certificate snap-in.

**Comment by Julaaaan** [comment]
Added.
